'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'fa' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  dir: 'rtl' | 'ltr';
}

// ترجمه‌های کامل - یکدست شده (بدون تکرار)
const translations: Record<Language, any> = {
  fa: {
    
    dashboard: 'داشبورد',
    courses: 'دوره‌ها',
    exams: 'آزمون‌ها',
    login: 'ورود',
    register: 'ثبت‌نام',
    logout: 'خروج',
    save: 'ذخیره',
    delete: 'حذف',
    cancel: 'انصراف',
    back: 'بازگشت',
    welcome: 'خوش آمدید',
    loading: 'در حال بارگذاری...',
    error: 'خطا رخ داده است',
    success: 'عملیات موفق بود',
    startExam: 'شروع آزمون',
    submit: 'ارسال',
    timeLeft: 'زمان باقیمانده',
    score: 'نمره',
    correct: 'صحیح',
    wrong: 'غلط',
    myCourses: 'دوره‌های من',
    myExams: 'آزمون‌های من',
    myNotes: 'یادداشت‌های من',
    savedResults: 'نتایج ذخیره شده',
    dailyTips: 'نکات روزانه',
    createCourse: 'ایجاد دوره جدید',
    createExam: 'ایجاد آزمون جدید',
    manageCourse: 'مدیریت دوره',

    course: {
      courseNotFound: 'کورس پیدا نشد',
      fetchError: 'خطا در دریافت اطلاعات',
      enrollSuccess: 'با موفقیت در کورس ثبت‌نام شدید!',
      enrollError: 'خطا در ثبت‌نام',
      backToList: 'بازگشت به لیست کورس‌ها',
      courseId: 'شناسه کورس',
      contents: 'محتوا',
      students: 'دانشجو',
      free: 'رایگان',
      toman: 'تومان',
      enrolled: 'در این کورس ثبت‌نام شده‌اید',
      viewContent: 'مشاهده محتوا',
      enrolling: 'در حال ثبت‌نام...',
      enrollInCourse: 'ثبت‌نام در این کورس',
      courseSyllabus: 'سرفصل‌های کورس',
      enrollRequired: 'نیاز به ثبت‌نام',
      checkingEnrollment: 'بررسی وضعیت ثبت‌نام...',
      loadError: 'خطا در بارگذاری اطلاعات کورس',
      titleRequired: 'عنوان را وارد کنید',
      urlRequired: 'آدرس فایل را وارد کنید',
      textRequired: 'متن محتوا را وارد کنید',
      contentAdded: 'محتوای جدید با موفقیت اضافه شد',
      contentAddError: 'خطا در ایجاد محتوا',
      confirmDeleteContent: 'آیا مطمئن هستید؟',
      contentDeleteError: 'خطا در حذف محتوا',
      publishStatusChanged: 'وضعیت انتشار تغییر کرد',
      publishError: 'خطا در تغییر وضعیت',
      changesSaved: 'تغییرات با موفقیت ذخیره شد',
      saveError: 'خطا در ذخیره تغییرات',
      confirmDeleteCourse: '⚠️ آیا از حذف این کورس اطمینان دارید؟ این عمل قابل بازگشت نیست!',
      invalidResponse: 'پاسخ نامعتبر از سرور',
      courseDeleted: '✅ کورس با موفقیت حذف شد',
      deleteError: '❌ خطا در حذف کورس',
      networkError: 'خطا در ارتباط با سرور',
      teacher: 'استاد',
      notFound: 'کورس پیدا نشد',
      backToDashboard: 'بازگشت به داشبورد',
      manage: 'مدیریت',
      published: 'منتشر شده',
      draft: 'پیش‌نویس',
      unpublish: 'لغو انتشار',
      publish: 'انتشار',
      saveChanges: 'ذخیره تغییرات',
      deleting: 'در حال حذف...',
      deleteCourse: 'حذف کورس',
      addContent: 'افزودن محتوا',
      contentTitle: 'عنوان محتوا',
      video: 'ویدئو',
      file: 'فایل',
      text: 'متن',
      fileUrl: 'آدرس فایل',
      textContent: 'متن محتوا',
      order: 'ترتیب (عدد)',
      makeFree: 'رایگان باشد',
      contentList: 'لیست محتوا',
      noContent: 'هنوز محتوایی اضافه نشده',
      locked: 'قفل',
      delete: 'حذف',
      languageLearningPlatform: 'پلتفرم آموزش زبان',
      viewCourse: 'مشاهده کورس',
      enterCourse: 'ورود به کورس',
      beginner: 'مبتدی',
      elementary: 'ابتدایی',
      intermediate: 'متوسط',
      upperIntermediate: 'متوسط به بالا',
      advanced: 'پیشرفته',
      contentError: 'خطا در دریافت محتوا',
      connectionError: 'خطا در اتصال به سرور',
      backToMyCourses: 'بازگشت به کورس‌های من',
      paymentRequired: 'برای دسترسی به همه محتوا باید پرداخت انجام شود',
      courseContent: 'محتوای کورس',
      items: 'مورد',
      noContentYet: 'هنوز محتوایی اضافه نشده است',
      lockedPaymentRequired: 'این محتوا قفل است - نیاز به پرداخت دارد',
      downloadFile: 'دانلود فایل',
    },

    teacher: {
      activeStudents: 'دانشجویان فعال',
      coursesTaught: 'دوره‌های تدریس شده',
      activeTests: 'آزمون‌های فعال',
      avgClassScore: 'میانگین نمره کلاس',
      assessments: 'ارزیابی‌ها',
      placementTest: 'آزمون تعیین سطح',
      dashboardSubtitle: 'پیشرفت برنامه درسی و دانشجویان خود را پیگیری کنید',
      createNewCourse: 'ایجاد دوره جدید',
      courseManagement: 'مدیریت دوره',
      viewAll: 'مشاهده همه',
      noCourses: 'هنوز دوره‌ای وجود ندارد',
      createFirstCourse: 'اولین دوره خود را ایجاد کنید',
      students: 'دانشجو',
      manage: 'مدیریت',
      needAssessment: 'به ارزیابی جدید نیاز دارید؟',
      examBuilderDesc: 'آزمون‌هایی با سوالات، فایل صوتی و زمان‌بندی ایجاد کنید',
      goToExamBuilder: 'ساخت آزمون',
      recentActivity: 'فعالیت‌های اخیر',
      noActivity: 'هیچ فعالیتی از دانشجویان ثبت نشده است',
      completed: 'تکمیل کرد',
      started: 'شروع کرد',
    },

    coursesPage: {
      title: 'دوره‌های آموزشی',
      subtitle: 'با بهترین اساتید، زبان یاد بگیرید و برای آزمون‌ها آماده شوید',
      searchPlaceholder: 'جستجوی دوره یا استاد...',
      filter: 'فیلتر',
      showing: 'نمایش',
      courses: 'دوره',
      noCoursesFound: 'دوره‌ای یافت نشد. فیلترها را تغییر دهید.',
      allLevels: 'همه سطوح',
      beginner: 'مبتدی',
      elementary: 'ابتدایی',
      intermediate: 'متوسط',
      upperIntermediate: 'متوسط به بالا',
      advanced: 'پیشرفته',
      allLanguages: 'همه زبان‌ها',
    },

   loginPage: {
  welcomeBack: 'خوش آمدید',
  signInMessage: 'به حساب کاربری خود وارد شوید',
  emailOrUsername: 'ایمیل یا نام کاربری',
  emailPlaceholder: 'ایمیل یا نام کاربری خود را وارد کنید',
  password: 'رمز عبور',
  passwordPlaceholder: 'رمز عبور خود را وارد کنید',
  signIn: 'ورود',
  signingIn: 'در حال ورود...',
  noAccount: 'حساب کاربری ندارید؟',
  createAccount: 'ثبت‌نام',
  error: 'ایمیل/نام کاربری یا رمز عبور اشتباه است',
  tagline: 'پلتفرم جامع شما برای آزمون زبان و ارزیابی یادگیری',
},
Home:'خانه',
// ✅ اینجا اضافه کنید:
home: {
  
  hero: {
    title: 'به LinguaTest خوش آمدید',
    subtitle: 'پلتفرم جامع شما برای یادگیری و آزمون زبان. گرامر، شنیداری و خواندن را تمرین کنید، نکات روزانه بگیرید و پیشرفت خود را پیگیری کنید.',
    startPlacement: 'شروع آزمون تعیین سطح',
    createAccount: 'ایجاد حساب کاربری',
    login: 'ورود',
  },
  examCategories: {
    title: 'دسته‌بندی آزمون‌ها',
    grammar: {
      title: 'آزمون گرامر',
      desc: 'توانایی خود را در بیان واضح و صحیح ایده‌ها در زبان هدف بسنجید.',
    },
    listening: {
      title: 'آزمون شنیداری',
      desc: 'درک خود را با مواد شنیداری متنوع بهبود بخشید.',
    },
    reading: {
      title: 'آزمون خواندن',
      desc: 'سرعت و حفظ مطلب خود را افزایش دهید.',
    },
    startTest: 'شروع آزمون',
  },
  popularCourses: {
    title: 'دوره‌های محبوب',
    subtitle: 'با محبوب‌ترین دوره‌های ما، که توسط اساتید خبره تدریس می‌شوند، یادگیری را شروع کنید',
    noCourses: 'هنوز دوره‌ای موجود نیست',
    viewCourse: 'مشاهده دوره',
    seeAll: 'مشاهده همه دوره‌ها',
    by: 'توسط',
  },
},

    registerPage: {
      passwordMismatch: 'رمز عبور و تکرار آن یکسان نیستند',
      passwordMinLength: 'رمز عبور باید حداقل ۶ کاراکتر باشد',
      error: 'خطا در ثبت‌نام',
      serverError: 'خطای سرور. لطفاً دوباره تلاش کنید.',
      joinTitle: 'به LinguaTest Pro بپیوندید',
      joinDescription: 'همین امروز حساب کاربری خود را ایجاد کنید و سفر یادگیری زبان خود را شروع کنید.',
      examsCount: 'آزمون موجود',
      studentsCount: 'دانشجوی فعال',
      createAccount: 'ایجاد حساب کاربری',
      fillDetails: 'جزئیات خود را برای شروع تکمیل کنید.',
      student: 'دانشجو',
      teacher: 'استاد',
      fullName: 'نام و نام خانوادگی',
      fullNamePlaceholder: 'John Doe',
      username: 'نام کاربری',
      usernamePlaceholder: 'johndoe',
      email: 'ایمیل',
      emailPlaceholder: 'john@example.com',
      password: 'رمز عبور',
      passwordPlaceholder: 'حداقل ۶ کاراکتر',
      confirmPassword: 'تکرار رمز عبور',
      confirmPasswordPlaceholder: 'رمز عبور را تکرار کنید',
      creating: 'در حال ایجاد حساب...',
      createButton: 'ایجاد حساب کاربری',
      haveAccount: 'قبلاً حساب کاربری دارید؟',
      signIn: 'ورود',
    },

    footer: {
      description: 'پلتفرم جامع شما برای آزمون زبان و یادگیری روزانه',
      aboutUs: 'درباره ما',
      ourStory: 'داستان ما',
      team: 'تیم ما',
      careers: 'فرصت‌های شغلی',
      support: 'پشتیبانی',
      faq: 'سوالات متداول',
      helpCenter: 'مرکز کمک',
      contactUs: 'تماس با ما',
      legal: 'قوانین',
      privacyPolicy: 'حریم خصوصی',
      termsOfService: 'شرایط استفاده',
      madeWith: 'ساخته شده با ❤️ برای زبان‌آموزان',
    },

    exam: {
      available: 'در دسترس',
      inProgress: 'در حال اجرا',
      past: 'گذشته',
      allExams: 'همه آزمون‌ها',
      pastResults: 'نتایج گذشته',
      starts: 'شروع',
      ends: 'پایان',
      mins: 'دقیقه',
      questions: 'سوال',
      continueExam: 'ادامه آزمون',
      startExam: 'شروع آزمون',
      viewResults: 'مشاهده نتایج',
      examsCompleted: 'آزمون‌های تکمیل شده',
      avgProficiency: 'میانگین مهارت',
      nextScheduled: 'برنامه بعدی',
      fromLastMonth: 'از ماه گذشته',
      welcomeBack: 'خوش آمدید',
      student: 'دانشجو',
      subtitle: 'گواهینامه‌های زبان خود را پیگیری کنید، ارزیابی‌های در حال انجام را ادامه دهید و آزمون‌های جدید مهارت را کشف کنید.',
      searchPlaceholder: 'جستجوی آزمون‌ها، دوره‌ها یا سطوح...',
      advancedFilters: 'فیلترهای پیشرفته',
      sortBy: 'مرتب‌سازی بر اساس',
      noExamsFound: 'هیچ آزمونی یافت نشد',
      tryAdjusting: 'سعی کنید جستجو یا فیلتر خود را تنظیم کنید',
      loadError: 'خطا در بارگذاری آزمون',
      submitError: 'خطا در ثبت نهایی',
      notFound: 'آزمون یافت نشد',
      backToExams: 'بازگشت به آزمون‌ها',
      of: 'از',
      answered: 'پاسخ داده شده',
      progress: 'پیشرفت آزمون',
      audioFile: 'فایل صوتی',
      readingText: 'متن Reading',
      question: 'سوال',
      previous: 'قبلی',
      submitting: 'در حال ثبت...',
      finishExam: 'پایان آزمون',
      next: 'بعدی',
      tempSaved: 'پاسخ‌ها ذخیره شد',
      tempSave: 'ذخیره موقت',
      timeExpired: 'زمان آزمون به پایان رسید. پاسخ‌ها به صورت خودکار ثبت شد.',
      confirmDelete: 'آیا از حذف این آزمون اطمینان دارید؟',
      deleteSuccess: 'آزمون با موفقیت حذف شد',
      deleteError: 'خطا در حذف آزمون',
      manageExams: 'مدیریت آزمون‌ها',
      newExam: 'آزمون جدید',
      noExams: 'هیچ آزمونی ایجاد نشده است',
      minutes: 'دقیقه',
      startDate: 'شروع',
      endDate: 'پایان',
      questionsCount: 'تعداد سوال',
      public: 'عمومی',
      private: 'خصوصی',
      edit: 'ویرایش',
      results: 'نتایج',
      back: 'بازگشت',
      editTest: 'ویرایش آزمون',
      createNewTest: 'ایجاد آزمون جدید',
      testDetails: 'جزئیات آزمون',
      testDetailsDesc: 'اطلاعات کلی درباره آزمون را وارد کنید.',
      testTitle: 'عنوان آزمون',
      titlePlaceholder: 'مثال: مبانی پایتون',
      testDescription: 'توضیحات آزمون',
      descriptionPlaceholder: 'دانشجویان روی چه چیزی تست می‌شوند؟',
      course: 'دوره',
      optional: 'اختیاری',
      noCourse: '-- بدون دوره --',
      difficultyLevel: 'سطح دشواری',
      easy: 'آسان',
      medium: 'متوسط',
      hard: 'سخت',
      duration: 'مدت (دقیقه)',
      studentAccess: 'دسترسی دانشجو',
      studentAccessDesc: 'کنترل کنید چه کسانی می‌توانند در این آزمون شرکت کنند.',
      publicAccess: 'دسترسی عمومی',
      publicAccessDesc: 'همه دانشجویان ثبت‌نام شده می‌توانند در این آزمون شرکت کنند.',
      restrictedAccess: 'دسترسی محدود',
      restrictedAccessDesc: 'فقط دانشجویانی با شناسه یا ایمیل مطابق می‌توانند به این آزمون دسترسی داشته باشند.',
      assignStudents: 'اختصاص به شناسه یا ایمیل دانشجو',
      commaSeparated: 'با کاما جدا شود',
      studentAccessNote: 'خالی بگذارید تا عمومی شود، یا سوییچ بالا را تغییر دهید.',
      testContent: 'محتوای آزمون',
      testContentDesc: 'به صورت اختیاری فایل صوتی یا متن Reading اضافه کنید که دانشجویان هنگام پاسخگویی به سوالات به آن مراجعه کنند.',
      noContent: 'بدون محتوا',
      audioFileLink: 'لینک فایل صوتی',
      textPassage: 'متن Reading',
      audioFileUrl: 'آدرس فایل صوتی',
      audioFileHint: 'آدرس فایل صوتی خود را وارد کنید (MP3, WAV و غیره). فایل باید به صورت عمومی قابل دسترسی باشد.',
      testLink: 'تست لینک',
      readingPassage: 'متن Reading',
      passagePlaceholder: 'متن Reading را در اینجا وارد کنید...',
      characters: 'کاراکتر',
      questionManagement: 'مدیریت سوالات',
      questionManagementDesc: 'سوالات این آزمون را اضافه، ویرایش یا حذف کنید. هر سوال ۴ گزینه A تا D دارد.',
      addNewQuestion: 'افزودن سوال جدید',
      newQuestion: 'سوال جدید',
      questionText: 'متن سوال',
      enterQuestion: 'سوال خود را وارد کنید...',
      option: 'گزینه',
      correctAnswer: 'پاسخ صحیح',
      addQuestion: 'افزودن سوال',
      currentQuestions: 'سوالات فعلی',
      currentQuestionsDesc: 'سوالات اضافه شده به این آزمون را مرور و مدیریت کنید.',
      save: 'ذخیره',
      correct: 'صحیح',
      questionCount: 'سوال',
      added: 'اضافه شد',
      saving: 'در حال ذخیره',
      updateTest: 'به‌روزرسانی آزمون',
      saveTest: 'ذخیره آزمون',
      updateSuccess: 'آزمون با موفقیت به‌روزرسانی شد!',
      createSuccess: 'آزمون با موفقیت ایجاد شد!',
      updateError: 'خطا در به‌روزرسانی آزمون',
      createError: 'خطا در ایجاد آزمون',
      networkError: 'خطای شبکه. دوباره تلاش کنید.',
      fillAllOptions: 'لطفاً سوال و هر ۴ گزینه را پر کنید.',
      titleRequired: 'عنوان آزمون الزامی است.',
      datesRequired: 'تاریخ شروع و پایان الزامی است.',
      atLeastOneQuestion: 'حداقل یک سوال اضافه کنید.',
    },

    examResult: {
      notFound: 'نتیجه‌ای برای این آزمون یافت نشد',
      fetchError: 'خطا در دریافت نتیجه',
      saveSuccess: 'نتیجه با موفقیت ذخیره شد',
      saveError: 'خطا در ذخیره نتیجه',
      confirmUnsave: 'آیا از حذف این نتیجه از داشبورد خود اطمینان دارید؟',
      unsaveSuccess: 'نتیجه با موفقیت از داشبورد حذف شد',
      unsaveError: 'خطا در حذف نتیجه',
      backToExams: 'بازگشت به آزمون‌ها',
      date: 'تاریخ',
      saving: 'در حال ذخیره...',
      saveToDashboard: 'ذخیره نتیجه در داشبورد',
      removing: 'در حال حذف...',
      removeFromDashboard: 'حذف از داشبورد',
      saved: 'ذخیره شده',
      score: 'نمره',
      correct: 'پاسخ صحیح',
      wrong: 'پاسخ غلط',
      of: 'از',
      reviewAnswers: 'بررسی پاسخ‌ها',
      correctAnswer: 'پاسخ صحیح',
      yourAnswer: 'پاسخ شما',
    },

    notes: {
      myNotes: 'یادداشت‌های من',
      newNote: 'یادداشت جدید',
      noNotes: 'هیچ یادداشتی ندارید.',
      confirmDelete: 'آیا از حذف این یادداشت اطمینان دارید؟',
      titlePlaceholder: 'عنوان',
      contentPlaceholder: 'متن یادداشت',
      save: 'ذخیره',
      cancel: 'انصراف',
      untitled: 'بدون عنوان',
      edit: 'ویرایش',
      delete: 'حذف',
      titleOptional: 'عنوان (اختیاری)',
      noteContent: 'متن یادداشت',
      saving: 'در حال ذخیره...',
    },

    dailyTip: {
      title: 'نکته روزانه',
      saveTip: 'ذخیره نکته',
      saved: 'ذخیره شد',
      deleteTip: 'حذف نکته',
      cannotDelete: 'این نکته قابل حذف نیست',
      confirmDelete: 'آیا از حذف این نکته اطمینان دارید؟',
      deleteSuccess: 'نکته با موفقیت حذف شد',
      deleteError: 'خطا در حذف نکته',
    },

    placement: {
      title: 'آزمون تعیین سطح',
      question: 'سوال',
      of: 'از',
      level: 'سطح',
      previous: 'قبلی',
      next: 'بعدی',
      finish: 'پایان آزمون',
      submitting: 'در حال ثبت...',
      submitError: 'خطا در ثبت آزمون',
    },

    placementResult: {
      title: 'نتیجه آزمون تعیین سطح',
      correctAnswers: 'تعداد پاسخ‌های صحیح',
      of: 'از',
      yourLevel: 'سطح زبان شما',
      score: 'امتیاز',
      viewCourses: 'مشاهده کورس‌های مناسب',
      goToDashboard: 'رفتن به داشبورد من',
      backToHome: 'بازگشت به خانه',
    },

    level: {
      A1: {
        title: 'شروع‌کننده (A1)',
        desc: 'می‌توانید عبارات ساده روزمره را بفهمید و استفاده کنید. در این سطح می‌توانید خودتان را معرفی کنید و سوالات ساده بپرسید.',
      },
      A2: {
        title: 'ابتدایی (A2)',
        desc: 'می‌توانید در موقعیت‌های آشنا ارتباط برقرار کنید. جملات ساده را می‌فهمید و می‌توانید درباره نیازهای روزمره صحبت کنید.',
      },
      B1: {
        title: 'متوسط (B1)',
        desc: 'می‌توانید در مورد موضوعات آشنا صحبت کنید و متن‌های ساده بنویسید. مکالمات روزمره را متوجه می‌شوید.',
      },
      B2: {
        title: 'متوسط به بالا (B2)',
        desc: 'می‌توانید با روانی نسبتاً خوب صحبت کنید. متون پیچیده‌تر را می‌فهمید و می‌توانید نظر خود را بیان کنید.',
      },
      C1: {
        title: 'پیشرفته (C1)',
        desc: 'می‌توانید متون پیچیده را بفهمید و به طور روان صحبت کنید. برای اهداف تحصیلی و حرفه‌ای مناسب است.',
      },
      C2: {
        title: 'مسلط (C2)',
        desc: 'می‌توانید مانند یک native speaker صحبت کنید. تمام متون را می‌فهمید و می‌توانید به راحتی ارتباط برقرار کنید.',
      },
    },
  },

  en: {
    home: {
  hero: {
    title: 'Master New Languages, Ace Every Test with LinguaTest',
    subtitle: 'Your comprehensive platform for language learning and testing. Practice grammar, listening, and reading skills, get daily tips, and track your progress.',
    startPlacement: 'Start Placement Test',
    createAccount: 'Create Account',
    login: 'Log In',
  },
  examCategories: {
    title: 'Explore Our Exam Categories',
    grammar: {
      title: 'Grammar Test',
      desc: 'Assess your ability to express ideas clearly and correctly in a target language.',
    },
    listening: {
      title: 'Listening Test',
      desc: 'Improve your comprehension with diverse audio materials.',
    },
    reading: {
      title: 'Reading Test',
      desc: 'Enhance your reading speed and retention.',
    },
    startTest: 'Start Test',
  },
  popularCourses: {
    title: 'Popular Courses',
    subtitle: 'Start learning with our most popular courses, taught by expert instructors',
    noCourses: 'No courses available yet.',
    viewCourse: 'View Course',
    seeAll: 'See All Courses',
    by: 'by',
  },
},

    dashboard: 'Dashboard',
    courses: 'Courses',
    exams: 'Exams',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
    back: 'Back',
    welcome: 'Welcome',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Operation successful',
    startExam: 'Start Exam',
    submit: 'Submit',
    timeLeft: 'Time Left',
    score: 'Score',
    correct: 'Correct',
    wrong: 'Wrong',
    myCourses: 'My Courses',
    myExams: 'My Exams',
    myNotes: 'My Notes',
    savedResults: 'Saved Results',
    dailyTips: 'Daily Tips',
    createCourse: 'Create New Course',
    createExam: 'Create New Exam',
    manageCourse: 'Manage Course',

    course: {
      courseNotFound: 'Course not found',
      fetchError: 'Error fetching course information',
      enrollSuccess: 'Successfully enrolled in the course!',
      enrollError: 'Enrollment failed',
      backToList: 'Back to Courses',
      courseId: 'Course ID',
      contents: 'contents',
      students: 'students',
      free: 'Free',
      toman: 'Toman',
      enrolled: 'You are enrolled in this course',
      viewContent: 'View Content',
      enrolling: 'Enrolling...',
      enrollInCourse: 'Enroll in this Course',
      courseSyllabus: 'Course Syllabus',
      enrollRequired: 'Enrollment Required',
      checkingEnrollment: 'Checking enrollment status...',
      loadError: 'Error loading course information',
      titleRequired: 'Title is required',
      urlRequired: 'File URL is required',
      textRequired: 'Text content is required',
      contentAdded: 'New content added successfully',
      contentAddError: 'Error adding content',
      confirmDeleteContent: 'Are you sure?',
      contentDeleteError: 'Error deleting content',
      publishStatusChanged: 'Publish status changed',
      publishError: 'Error changing publish status',
      changesSaved: 'Changes saved successfully',
      saveError: 'Error saving changes',
      confirmDeleteCourse: '⚠️ Are you sure you want to delete this course? This action cannot be undone!',
      invalidResponse: 'Invalid server response',
      courseDeleted: '✅ Course deleted successfully',
      deleteError: '❌ Error deleting course',
      networkError: 'Network error',
      teacher: 'Teacher',
      notFound: 'Course not found',
      backToDashboard: 'Back to Dashboard',
      manage: 'Manage',
      published: 'Published',
      draft: 'Draft',
      unpublish: 'Unpublish',
      publish: 'Publish',
      saveChanges: 'Save Changes',
      deleting: 'Deleting...',
      deleteCourse: 'Delete Course',
      addContent: 'Add Content',
      contentTitle: 'Content Title',
      video: 'Video',
      file: 'File',
      text: 'Text',
      fileUrl: 'File URL',
      textContent: 'Text Content',
      order: 'Order (number)',
      makeFree: 'Make free',
      contentList: 'Content List',
      noContent: 'No content added yet',
      locked: 'Locked',
      delete: 'Delete',
      languageLearningPlatform: 'Language Learning Platform',
      viewCourse: 'View Course',
      enterCourse: 'Enter Course',
      beginner: 'Beginner',
      elementary: 'Elementary',
      intermediate: 'Intermediate',
      upperIntermediate: 'Upper Intermediate',
      advanced: 'Advanced',
      contentError: 'Error loading content',
      connectionError: 'Connection error',
      backToMyCourses: 'Back to My Courses',
      paymentRequired: 'Payment required to access all content',
      courseContent: 'Course Content',
      items: 'items',
      noContentYet: 'No content added yet',
      lockedPaymentRequired: 'This content is locked - payment required',
      downloadFile: 'Download File',
    },

    teacher: {
      activeStudents: 'Active Students',
      coursesTaught: 'Courses Taught',
      activeTests: 'Active Tests',
      avgClassScore: 'Avg. Class Score',
      assessments: 'Assessments',
      placementTest: 'Placement Test',
      dashboardSubtitle: "Track your curriculum and students' progress here.",
      createNewCourse: 'Create New Course',
      courseManagement: 'Course Management',
      viewAll: 'View All',
      noCourses: 'No courses yet',
      createFirstCourse: 'Create your first course',
      students: 'Students',
      manage: 'Manage',
      needAssessment: 'Need a new assessment?',
      examBuilderDesc: 'Create exams with questions, audio and timed sessions.',
      goToExamBuilder: 'Go to Exam Builder',
      recentActivity: 'Recent Activity',
      noActivity: 'No recent student activity',
      completed: 'completed',
      started: 'started',
    },

    coursesPage: {
      title: 'Educational Courses',
      subtitle: 'Learn languages with the best teachers and prepare for exams',
      searchPlaceholder: 'Search courses or teachers...',
      filter: 'Filter',
      showing: 'Showing',
      courses: 'courses',
      noCoursesFound: 'No courses found. Change your filters.',
      allLevels: 'All Levels',
      beginner: 'Beginner',
      elementary: 'Elementary',
      intermediate: 'Intermediate',
      upperIntermediate: 'Upper Intermediate',
      advanced: 'Advanced',
      allLanguages: 'All Languages',
    },

    loginPage: {
      welcomeBack: 'Welcome Back',
      signInMessage: 'Sign in to your LinguaTest Pro account.',
      emailOrUsername: 'Email or Username',
      emailPlaceholder: 'Enter your email or username',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      signIn: 'Sign In',
      signingIn: 'Signing in...',
      noAccount: "Don't have an account?",
      createAccount: 'Create Account',
      error: 'Invalid email/username or password',
      tagline: 'Your comprehensive platform for language testing and learning assessment.',
    },

    registerPage: {
      passwordMismatch: 'Passwords do not match',
      passwordMinLength: 'Password must be at least 6 characters',
      error: 'Registration failed',
      serverError: 'Server error. Please try again.',
      joinTitle: 'Join LinguaTest Pro',
      joinDescription: 'Create your account and start your language learning journey today.',
      examsCount: 'Exams Available',
      studentsCount: 'Active Students',
      createAccount: 'Create Account',
      fillDetails: 'Fill in your details to get started.',
      student: 'Student',
      teacher: 'Teacher',
      fullName: 'Full Name',
      fullNamePlaceholder: 'John Doe',
      username: 'Username',
      usernamePlaceholder: 'johndoe',
      email: 'Email',
      emailPlaceholder: 'john@example.com',
      password: 'Password',
      passwordPlaceholder: 'Min 6 characters',
      confirmPassword: 'Confirm Password',
      confirmPasswordPlaceholder: 'Repeat your password',
      creating: 'Creating Account...',
      createButton: 'Create Account',
      haveAccount: 'Already have an account?',
      signIn: 'Sign In',
    },

    footer: {
      description: 'Your comprehensive platform for language testing and daily learning.',
      aboutUs: 'About Us',
      ourStory: 'Our Story',
      team: 'Team',
      careers: 'Careers',
      support: 'Support',
      faq: 'FAQ',
      helpCenter: 'Help Center',
      contactUs: 'Contact Us',
      legal: 'Legal',
      privacyPolicy: 'Privacy Policy',
      termsOfService: 'Terms of Service',
      madeWith: 'Made with ❤️ for language learners',
    },

    exam: {
      available: 'Available',
      inProgress: 'In Progress',
      past: 'Past',
      allExams: 'All Exams',
      pastResults: 'Past Results',
      starts: 'Starts',
      ends: 'Ends',
      mins: 'mins',
      questions: 'Questions',
      continueExam: 'Continue Exam',
      startExam: 'Start Exam',
      viewResults: 'View Results',
      examsCompleted: 'Exams Completed',
      avgProficiency: 'Avg. Proficiency',
      nextScheduled: 'Next Scheduled',
      fromLastMonth: 'from last month',
      welcomeBack: 'Welcome Back',
      student: 'Student',
      subtitle: 'Track your language certifications, continue ongoing assessments, and discover new proficiency tests.',
      searchPlaceholder: 'Search exams, courses, or levels...',
      advancedFilters: 'Advanced Filters',
      sortBy: 'Sort by',
      noExamsFound: 'No exams found',
      tryAdjusting: 'Try adjusting your search or filter',
      loadError: 'Error loading exam',
      submitError: 'Error submitting exam',
      notFound: 'Exam not found',
      backToExams: 'Back to Exams',
      of: 'of',
      answered: 'answered',
      progress: 'Exam Progress',
      audioFile: 'Audio File',
      readingText: 'Reading Passage',
      question: 'Question',
      previous: 'Previous',
      submitting: 'Submitting...',
      finishExam: 'Finish Exam',
      next: 'Next',
      tempSaved: 'Answers saved',
      tempSave: 'Save Progress',
      timeExpired: 'Time is up! Your answers have been automatically submitted.',
      confirmDelete: 'Are you sure you want to delete this exam?',
      deleteSuccess: 'Exam deleted successfully',
      deleteError: 'Error deleting exam',
      manageExams: 'Manage Exams',
      newExam: 'New Exam',
      noExams: 'No exams created yet',
      minutes: 'minutes',
      startDate: 'Start',
      endDate: 'End',
      questionsCount: 'Questions',
      public: 'Public',
      private: 'Private',
      edit: 'Edit',
      results: 'Results',
      back: 'Back',
      editTest: 'Edit Test',
      createNewTest: 'Create New Test',
      testDetails: 'Test Details',
      testDetailsDesc: 'Provide general information about the test.',
      testTitle: 'Test Title',
      titlePlaceholder: 'e.g. Introduction to Python Basics',
      testDescription: 'Test Description',
      descriptionPlaceholder: 'What will students be tested on?',
      course: 'Course',
      optional: 'optional',
      noCourse: '-- No Course --',
      difficultyLevel: 'Difficulty Level',
      easy: 'Easy',
      medium: 'Medium',
      hard: 'Hard',
      duration: 'Duration (min)',
      studentAccess: 'Student Access',
      studentAccessDesc: 'Control who can take this test.',
      publicAccess: 'Public access',
      publicAccessDesc: 'All enrolled students can take this test. Toggle to restrict access.',
      restrictedAccess: 'Restricted access',
      restrictedAccessDesc: 'Only students with matching IDs or emails can access this test.',
      assignStudents: 'Assign to Student IDs or Emails',
      commaSeparated: 'comma-separated',
      studentAccessNote: 'Leave empty to make public, or toggle the switch above.',
      testContent: 'Test Content',
      testContentDesc: 'Optionally add audio or a reading passage that students will refer to while answering questions.',
      noContent: 'No Content',
      audioFileLink: 'Audio File Link',
      textPassage: 'Text Passage',
      audioFileUrl: 'Audio File URL',
      audioFileHint: 'Enter the URL of your audio file (MP3, WAV, etc.). The file should be publicly accessible.',
      testLink: 'Test Link',
      readingPassage: 'Reading Passage',
      passagePlaceholder: 'Paste or type the reading passage here. Students will read this before answering the questions...',
      characters: 'characters',
      questionManagement: 'Question Management',
      questionManagementDesc: 'Add, edit, or remove questions for this test. Each question has 4 options (A–D).',
      addNewQuestion: 'Add New Question',
      newQuestion: 'New Question',
      questionText: 'Question Text',
      enterQuestion: 'Enter your question...',
      option: 'Option',
      correctAnswer: 'Correct Answer',
      addQuestion: 'Add Question',
      currentQuestions: 'Current Questions',
      currentQuestionsDesc: 'Review and manage the questions added to this test.',
      save: 'Save',
      correct: 'Correct',
      questionCount: 'question',
      added: 'added',
      saving: 'Saving',
      updateTest: 'Update Test',
      saveTest: 'Save Test',
      updateSuccess: 'Test updated successfully!',
      createSuccess: 'Test created successfully!',
      updateError: 'Failed to update test',
      createError: 'Failed to create test',
      networkError: 'Network error. Try again.',
      fillAllOptions: 'Please fill in the question and all 4 options.',
      titleRequired: 'Test title is required.',
      datesRequired: 'Start and end dates are required.',
      atLeastOneQuestion: 'Add at least one question.',
    },

    examResult: {
      notFound: 'No result found for this exam',
      fetchError: 'Error fetching result',
      saveSuccess: 'Result saved successfully',
      saveError: 'Error saving result',
      confirmUnsave: 'Are you sure you want to remove this result from your dashboard?',
      unsaveSuccess: 'Result removed from dashboard',
      unsaveError: 'Error removing result',
      backToExams: 'Back to Exams',
      date: 'Date',
      saving: 'Saving...',
      saveToDashboard: 'Save Result to Dashboard',
      removing: 'Removing...',
      removeFromDashboard: 'Remove from Dashboard',
      saved: 'Saved',
      score: 'Score',
      correct: 'Correct',
      wrong: 'Wrong',
      of: 'of',
      reviewAnswers: 'Review Answers',
      correctAnswer: 'Correct Answer',
      yourAnswer: 'Your Answer',
    },

    notes: {
      myNotes: 'My Notes',
      newNote: 'New Note',
      noNotes: 'No notes yet.',
      confirmDelete: 'Are you sure you want to delete this note?',
      titlePlaceholder: 'Title',
      contentPlaceholder: 'Note content',
      save: 'Save',
      cancel: 'Cancel',
      untitled: 'Untitled',
      edit: 'Edit',
      delete: 'Delete',
      titleOptional: 'Title (optional)',
      noteContent: 'Note content',
      saving: 'Saving...',
    },

    dailyTip: {
      title: 'Daily Learning Tip',
      saveTip: 'Save Tip',
      saved: 'Saved',
      deleteTip: 'Delete Tip',
      cannotDelete: 'This tip cannot be deleted',
      confirmDelete: 'Are you sure you want to delete this tip?',
      deleteSuccess: 'Tip deleted successfully',
      deleteError: 'Error deleting tip',
    },

    placement: {
      title: 'Placement Test',
      question: 'Question',
      of: 'of',
      level: 'Level',
      previous: 'Previous',
      next: 'Next',
      finish: 'Finish Exam',
      submitting: 'Submitting...',
      submitError: 'Error submitting exam',
    },

    placementResult: {
      title: 'Placement Test Result',
      correctAnswers: 'Correct answers',
      of: 'of',
      yourLevel: 'Your language level',
      score: 'Score',
      viewCourses: 'Browse Suitable Courses',
      goToDashboard: 'Go to My Dashboard',
      backToHome: 'Back to Home',
    },

    level: {
      A1: {
        title: 'Beginner (A1)',
        desc: 'You can understand and use basic everyday expressions. At this level, you can introduce yourself and ask simple questions.',
      },
      A2: {
        title: 'Elementary (A2)',
        desc: 'You can communicate in familiar situations. You understand simple sentences and can talk about daily needs.',
      },
      B1: {
        title: 'Intermediate (B1)',
        desc: 'You can speak about familiar topics and write simple texts. You understand everyday conversations.',
      },
      B2: {
        title: 'Upper Intermediate (B2)',
        desc: 'You can speak with relative fluency. You understand more complex texts and can express your opinions.',
      },
      C1: {
        title: 'Advanced (C1)',
        desc: 'You can understand complex texts and speak fluently. Suitable for academic and professional purposes.',
      },
      C2: {
        title: 'Proficient (C2)',
        desc: 'You can speak like a native speaker. You understand all texts and can communicate easily.',
      },
    },
  },

  de: {
    
    Home:'Haus',
home: {
  hero: {
    title: 'Neue Sprachen meistern, Jeden Test bestehen mit LinguaTest',
    subtitle: 'Ihre umfassende Plattform für Sprachlernen und Tests. Üben Sie Grammatik, Hörverstehen und Lesefähigkeiten, erhalten Sie tägliche Tipps und verfolgen Sie Ihren Fortschritt.',
    startPlacement: 'Einstufungstest starten',
    createAccount: 'Konto erstellen',
    login: 'Anmelden',
  },
  examCategories: {
    title: 'Entdecken Sie unsere Prüfungskategorien',
    grammar: {
      title: 'Grammatiktest',
      desc: 'Bewerten Sie Ihre Fähigkeit, Ideen klar und korrekt in einer Zielsprache auszudrücken.',
    },
    listening: {
      title: 'Hörverständnistest',
      desc: 'Verbessern Sie Ihr Verständnis mit vielfältigen Audiomaterialien.',
    },
    reading: {
      title: 'Lesetest',
      desc: 'Verbessern Sie Ihre Lesegeschwindigkeit und Ihr Behalten.',
    },
    startTest: 'Test starten',
  },
  popularCourses: {
    title: 'Beliebte Kurse',
    subtitle: 'Beginnen Sie das Lernen mit unseren beliebtesten Kursen, die von erfahrenen Dozenten unterrichtet werden',
    noCourses: 'Noch keine Kurse verfügbar.',
    viewCourse: 'Kurs ansehen',
    seeAll: 'Alle Kurse anzeigen',
    by: 'von',
  },
},
    dashboard: 'Dashboard',
    courses: 'Kurse',
    exams: 'Prüfungen',
    login: 'Anmelden',
    register: 'Registrieren',
    logout: 'Abmelden',
    save: 'Speichern',
    delete: 'Löschen',
    cancel: 'Abbrechen',
    back: 'Zurück',
    welcome: 'Willkommen',
    loading: 'Laden...',
    error: 'Ein Fehler ist aufgetreten',
    success: 'Erfolgreich',
    startExam: 'Prüfung starten',
    submit: 'Einreichen',
    timeLeft: 'Verbleibende Zeit',
    score: 'Punktzahl',
    correct: 'Richtig',
    wrong: 'Falsch',
    myCourses: 'Meine Kurse',
    myExams: 'Meine Prüfungen',
    myNotes: 'Meine Notizen',
    savedResults: 'Gespeicherte Ergebnisse',
    dailyTips: 'Tägliche Tipps',
    createCourse: 'Neuen Kurs erstellen',
    createExam: 'Neue Prüfung erstellen',
    manageCourse: 'Kurs verwalten',

    course: {
      courseNotFound: 'Kurs nicht gefunden',
      fetchError: 'Fehler beim Abrufen der Kursinformationen',
      enrollSuccess: 'Erfolgreich im Kurs eingeschrieben!',
      enrollError: 'Einschreibung fehlgeschlagen',
      backToList: 'Zurück zu den Kursen',
      courseId: 'Kurs-ID',
      contents: 'Inhalte',
      students: 'Studenten',
      free: 'Kostenlos',
      toman: 'Toman',
      enrolled: 'Sie sind in diesem Kurs eingeschrieben',
      viewContent: 'Inhalt anzeigen',
      enrolling: 'Einschreiben...',
      enrollInCourse: 'In diesen Kurs einschreiben',
      courseSyllabus: 'Kurslehrplan',
      enrollRequired: 'Einschreibung erforderlich',
      checkingEnrollment: 'Einschreibungsstatus wird überprüft...',
      loadError: 'Fehler beim Laden der Kursinformationen',
      titleRequired: 'Titel ist erforderlich',
      urlRequired: 'Datei-URL ist erforderlich',
      textRequired: 'Textinhalt ist erforderlich',
      contentAdded: 'Neuer Inhalt erfolgreich hinzugefügt',
      contentAddError: 'Fehler beim Hinzufügen des Inhalts',
      confirmDeleteContent: 'Sind Sie sicher?',
      contentDeleteError: 'Fehler beim Löschen des Inhalts',
      publishStatusChanged: 'Veröffentlichungsstatus geändert',
      publishError: 'Fehler beim Ändern des Veröffentlichungsstatus',
      changesSaved: 'Änderungen erfolgreich gespeichert',
      saveError: 'Fehler beim Speichern der Änderungen',
      confirmDeleteCourse: '⚠️ Sind Sie sicher, dass Sie diesen Kurs löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden!',
      invalidResponse: 'Ungültige Serverantwort',
      courseDeleted: '✅ Kurs erfolgreich gelöscht',
      deleteError: '❌ Fehler beim Löschen des Kurses',
      networkError: 'Netzwerkfehler',
      teacher: 'Lehrer',
      notFound: 'Kurs nicht gefunden',
      backToDashboard: 'Zurück zum Dashboard',
      manage: 'Verwalten',
      published: 'Veröffentlicht',
      draft: 'Entwurf',
      unpublish: 'Veröffentlichung aufheben',
      publish: 'Veröffentlichen',
      saveChanges: 'Änderungen speichern',
      deleting: 'Wird gelöscht...',
      deleteCourse: 'Kurs löschen',
      addContent: 'Inhalt hinzufügen',
      contentTitle: 'Inhaltstitel',
      video: 'Video',
      file: 'Datei',
      text: 'Text',
      fileUrl: 'Datei-URL',
      textContent: 'Textinhalt',
      order: 'Reihenfolge (Zahl)',
      makeFree: 'Kostenlos machen',
      contentList: 'Inhaltsliste',
      noContent: 'Noch kein Inhalt hinzugefügt',
      locked: 'Gesperrt',
      delete: 'Löschen',
      languageLearningPlatform: 'Sprachlernplattform',
      viewCourse: 'Kurs ansehen',
      enterCourse: 'Kurs betreten',
      beginner: 'Anfänger',
      elementary: 'Grundlegend',
      intermediate: 'Mittelstufe',
      upperIntermediate: 'Obere Mittelstufe',
      advanced: 'Fortgeschritten',
      contentError: 'Fehler beim Laden des Inhalts',
      connectionError: 'Verbindungsfehler',
      backToMyCourses: 'Zurück zu meinen Kursen',
      paymentRequired: 'Zahlung erforderlich, um auf alle Inhalte zuzugreifen',
      courseContent: 'Kursinhalt',
      items: 'Elemente',
      noContentYet: 'Noch kein Inhalt hinzugefügt',
      lockedPaymentRequired: 'Dieser Inhalt ist gesperrt - Zahlung erforderlich',
      downloadFile: 'Datei herunterladen',
    },

    teacher: {
      activeStudents: 'Aktive Studenten',
      coursesTaught: 'Unterrichtete Kurse',
      activeTests: 'Aktive Tests',
      avgClassScore: 'Durchschnittliche Klassenpunktzahl',
      assessments: 'Bewertungen',
      placementTest: 'Einstufungstest',
      dashboardSubtitle: 'Verfolgen Sie hier Ihren Lehrplan und den Fortschritt Ihrer Studenten.',
      createNewCourse: 'Neuen Kurs erstellen',
      courseManagement: 'Kursverwaltung',
      viewAll: 'Alle anzeigen',
      noCourses: 'Noch keine Kurse',
      createFirstCourse: 'Erstellen Sie Ihren ersten Kurs',
      students: 'Studenten',
      manage: 'Verwalten',
      needAssessment: 'Benötigen Sie eine neue Bewertung?',
      examBuilderDesc: 'Erstellen Sie Prüfungen mit Fragen, Audio und zeitgesteuerten Sitzungen.',
      goToExamBuilder: 'Prüfungsgenerator',
      recentActivity: 'Letzte Aktivitäten',
      noActivity: 'Keine aktuellen Studentenaktivitäten',
      completed: 'abgeschlossen',
      started: 'gestartet',
    },

    coursesPage: {
      title: 'Bildungskurse',
      subtitle: 'Lernen Sie Sprachen mit den besten Lehrern und bereiten Sie sich auf Prüfungen vor',
      searchPlaceholder: 'Kurse oder Lehrer suchen...',
      filter: 'Filter',
      showing: 'Zeige',
      courses: 'Kurse',
      noCoursesFound: 'Keine Kurse gefunden. Ändern Sie Ihre Filter.',
      allLevels: 'Alle Niveaus',
      beginner: 'Anfänger',
      elementary: 'Grundlegend',
      intermediate: 'Mittelstufe',
      upperIntermediate: 'Obere Mittelstufe',
      advanced: 'Fortgeschritten',
      allLanguages: 'Alle Sprachen',
    },

    loginPage: {
      welcomeBack: 'Willkommen zurück',
      signInMessage: 'Melden Sie sich bei Ihrem LinguaTest Pro-Konto an.',
      emailOrUsername: 'E-Mail oder Benutzername',
      emailPlaceholder: 'Geben Sie Ihre E-Mail oder Ihren Benutzernamen ein',
      password: 'Passwort',
      passwordPlaceholder: 'Geben Sie Ihr Passwort ein',
      signIn: 'Anmelden',
      signingIn: 'Anmelden...',
      noAccount: 'Sie haben kein Konto?',
      createAccount: 'Konto erstellen',
      error: 'Ungültige E-Mail / Benutzername oder Passwort',
      tagline: 'Ihre umfassende Plattform für Sprachtests und Lernbewertungen.',
    },

    registerPage: {
      passwordMismatch: 'Passwörter stimmen nicht überein',
      passwordMinLength: 'Passwort muss mindestens 6 Zeichen lang sein',
      error: 'Registrierung fehlgeschlagen',
      serverError: 'Serverfehler. Bitte versuchen Sie es erneut.',
      joinTitle: 'Werden Sie Mitglied bei LinguaTest Pro',
      joinDescription: 'Erstellen Sie noch heute Ihr Konto und starten Sie Ihre Sprachlernreise.',
      examsCount: 'Prüfungen verfügbar',
      studentsCount: 'Aktive Studenten',
      createAccount: 'Konto erstellen',
      fillDetails: 'Geben Sie Ihre Daten ein, um zu beginnen.',
      student: 'Student',
      teacher: 'Lehrer',
      fullName: 'Vollständiger Name',
      fullNamePlaceholder: 'John Doe',
      username: 'Benutzername',
      usernamePlaceholder: 'johndoe',
      email: 'E-Mail',
      emailPlaceholder: 'john@example.com',
      password: 'Passwort',
      passwordPlaceholder: 'Mindestens 6 Zeichen',
      confirmPassword: 'Passwort bestätigen',
      confirmPasswordPlaceholder: 'Wiederholen Sie Ihr Passwort',
      creating: 'Konto wird erstellt...',
      createButton: 'Konto erstellen',
      haveAccount: 'Sie haben bereits ein Konto?',
      signIn: 'Anmelden',
    },

    footer: {
      description: 'Ihre umfassende Plattform für Sprachtests und tägliches Lernen.',
      aboutUs: 'Über uns',
      ourStory: 'Unsere Geschichte',
      team: 'Team',
      careers: 'Karriere',
      support: 'Support',
      faq: 'FAQ',
      helpCenter: 'Hilfezentrum',
      contactUs: 'Kontakt',
      legal: 'Rechtliches',
      privacyPolicy: 'Datenschutz',
      termsOfService: 'Nutzungsbedingungen',
      madeWith: 'Gemacht mit ❤️ für Sprachlerner',
    },

    exam: {
      available: 'Verfügbar',
      inProgress: 'In Bearbeitung',
      past: 'Abgeschlossen',
      allExams: 'Alle Prüfungen',
      pastResults: 'Vergangene Ergebnisse',
      starts: 'Beginnt',
      ends: 'Endet',
      mins: 'Minuten',
      questions: 'Fragen',
      continueExam: 'Prüfung fortsetzen',
      startExam: 'Prüfung starten',
      viewResults: 'Ergebnisse anzeigen',
      examsCompleted: 'Abgeschlossene Prüfungen',
      avgProficiency: 'Durchschnittliche Kenntnisse',
      nextScheduled: 'Nächster Termin',
      fromLastMonth: 'seit letztem Monat',
      welcomeBack: 'Willkommen zurück',
      student: 'Student',
      subtitle: 'Verfolgen Sie Ihre Sprachzertifikate, setzen Sie laufende Bewertungen fort und entdecken Sie neue Einstufungstests.',
      searchPlaceholder: 'Prüfungen, Kurse oder Niveaus durchsuchen...',
      advancedFilters: 'Erweiterte Filter',
      sortBy: 'Sortieren nach',
      noExamsFound: 'Keine Prüfungen gefunden',
      tryAdjusting: 'Passen Sie Ihre Suche oder Filter an',
      loadError: 'Fehler beim Laden der Prüfung',
      submitError: 'Fehler beim Einreichen der Prüfung',
      notFound: 'Prüfung nicht gefunden',
      backToExams: 'Zurück zu den Prüfungen',
      of: 'von',
      answered: 'beantwortet',
      progress: 'Prüfungsfortschritt',
      audioFile: 'Audiodatei',
      readingText: 'Lesetext',
      question: 'Frage',
      previous: 'Zurück',
      submitting: 'Wird eingereicht...',
      finishExam: 'Prüfung beenden',
      next: 'Weiter',
      tempSaved: 'Antworten gespeichert',
      tempSave: 'Fortschritt speichern',
      timeExpired: 'Die Zeit ist abgelaufen! Ihre Antworten wurden automatisch eingereicht.',
      confirmDelete: 'Möchten Sie diese Prüfung wirklich löschen?',
      deleteSuccess: 'Prüfung erfolgreich gelöscht',
      deleteError: 'Fehler beim Löschen der Prüfung',
      manageExams: 'Prüfungen verwalten',
      newExam: 'Neue Prüfung',
      noExams: 'Noch keine Prüfungen erstellt',
      minutes: 'Minuten',
      startDate: 'Beginn',
      endDate: 'Ende',
      questionsCount: 'Fragen',
      public: 'Öffentlich',
      private: 'Privat',
      edit: 'Bearbeiten',
      results: 'Ergebnisse',
      back: 'Zurück',
      editTest: 'Prüfung bearbeiten',
      createNewTest: 'Neue Prüfung erstellen',
      testDetails: 'Prüfungsdetails',
      testDetailsDesc: 'Geben Sie allgemeine Informationen zur Prüfung an.',
      testTitle: 'Prüfungstitel',
      titlePlaceholder: 'z.B. Einführung in Python',
      testDescription: 'Prüfungsbeschreibung',
      descriptionPlaceholder: 'Worüber werden die Studenten getestet?',
      course: 'Kurs',
      optional: 'optional',
      noCourse: '-- Kein Kurs --',
      difficultyLevel: 'Schwierigkeitsgrad',
      easy: 'Einfach',
      medium: 'Mittel',
      hard: 'Schwer',
      duration: 'Dauer (Minuten)',
      studentAccess: 'Studentenzugriff',
      studentAccessDesc: 'Kontrollieren Sie, wer an dieser Prüfung teilnehmen kann.',
      publicAccess: 'Öffentlicher Zugriff',
      publicAccessDesc: 'Alle eingeschriebenen Studenten können an dieser Prüfung teilnehmen.',
      restrictedAccess: 'Eingeschränkter Zugriff',
      restrictedAccessDesc: 'Nur Studenten mit passenden IDs oder E-Mails können auf diese Prüfung zugreifen.',
      assignStudents: 'Studenten-IDs oder E-Mails zuweisen',
      commaSeparated: 'kommagetrennt',
      studentAccessNote: 'Leer lassen, um öffentlich zu machen, oder den Schalter oben umschalten.',
      testContent: 'Prüfungsinhalt',
      testContentDesc: 'Fügen Sie optional Audio oder einen Lesetext hinzu, auf den sich die Studenten beim Beantworten der Fragen beziehen können.',
      noContent: 'Kein Inhalt',
      audioFileLink: 'Audiodatei-Link',
      textPassage: 'Lesetext',
      audioFileUrl: 'Audiodatei-URL',
      audioFileHint: 'Geben Sie die URL Ihrer Audiodatei ein (MP3, WAV usw.). Die Datei sollte öffentlich zugänglich sein.',
      testLink: 'Link testen',
      readingPassage: 'Lesetext',
      passagePlaceholder: 'Fügen Sie hier den Lesetext ein...',
      characters: 'Zeichen',
      questionManagement: 'Fragenverwaltung',
      questionManagementDesc: 'Fügen Sie Fragen hinzu, bearbeiten oder entfernen Sie sie. Jede Frage hat 4 Optionen (A–D).',
      addNewQuestion: 'Neue Frage hinzufügen',
      newQuestion: 'Neue Frage',
      questionText: 'Fragentext',
      enterQuestion: 'Geben Sie Ihre Frage ein...',
      option: 'Option',
      correctAnswer: 'Richtige Antwort',
      addQuestion: 'Frage hinzufügen',
      currentQuestions: 'Aktuelle Fragen',
      currentQuestionsDesc: 'Überprüfen und verwalten Sie die Fragen, die dieser Prüfung hinzugefügt wurden.',
      save: 'Speichern',
      correct: 'Richtig',
      questionCount: 'Frage',
      added: 'hinzugefügt',
      saving: 'Wird gespeichert',
      updateTest: 'Prüfung aktualisieren',
      saveTest: 'Prüfung speichern',
      updateSuccess: 'Prüfung erfolgreich aktualisiert!',
      createSuccess: 'Prüfung erfolgreich erstellt!',
      updateError: 'Fehler beim Aktualisieren der Prüfung',
      createError: 'Fehler beim Erstellen der Prüfung',
      networkError: 'Netzwerkfehler. Versuchen Sie es erneut.',
      fillAllOptions: 'Bitte füllen Sie die Frage und alle 4 Optionen aus.',
      titleRequired: 'Prüfungstitel ist erforderlich.',
      datesRequired: 'Start- und Enddatum sind erforderlich.',
      atLeastOneQuestion: 'Fügen Sie mindestens eine Frage hinzu.',
    },

    examResult: {
      notFound: 'Kein Ergebnis für diese Prüfung gefunden',
      fetchError: 'Fehler beim Abrufen des Ergebnisses',
      saveSuccess: 'Ergebnis erfolgreich gespeichert',
      saveError: 'Fehler beim Speichern des Ergebnisses',
      confirmUnsave: 'Möchten Sie dieses Ergebnis wirklich aus Ihrem Dashboard entfernen?',
      unsaveSuccess: 'Ergebnis aus dem Dashboard entfernt',
      unsaveError: 'Fehler beim Entfernen des Ergebnisses',
      backToExams: 'Zurück zu den Prüfungen',
      date: 'Datum',
      saving: 'Wird gespeichert...',
      saveToDashboard: 'Ergebnis im Dashboard speichern',
      removing: 'Wird entfernt...',
      removeFromDashboard: 'Aus Dashboard entfernen',
      saved: 'Gespeichert',
      score: 'Punktzahl',
      correct: 'Richtig',
      wrong: 'Falsch',
      of: 'von',
      reviewAnswers: 'Antworten überprüfen',
      correctAnswer: 'Richtige Antwort',
      yourAnswer: 'Ihre Antwort',
    },

    notes: {
      myNotes: 'Meine Notizen',
      newNote: 'Neue Notiz',
      noNotes: 'Noch keine Notizen.',
      confirmDelete: 'Möchten Sie diese Notiz wirklich löschen?',
      titlePlaceholder: 'Titel',
      contentPlaceholder: 'Notizinhalt',
      save: 'Speichern',
      cancel: 'Abbrechen',
      untitled: 'Ohne Titel',
      edit: 'Bearbeiten',
      delete: 'Löschen',
      titleOptional: 'Titel (optional)',
      noteContent: 'Notizinhalt',
      saving: 'Wird gespeichert...',
    },

    dailyTip: {
      title: 'Täglicher Lerntipp',
      saveTip: 'Tipp speichern',
      saved: 'Gespeichert',
      deleteTip: 'Tipp löschen',
      cannotDelete: 'Dieser Tipp kann nicht gelöscht werden',
      confirmDelete: 'Möchten Sie diesen Tipp wirklich löschen?',
      deleteSuccess: 'Tipp erfolgreich gelöscht',
      deleteError: 'Fehler beim Löschen des Tipps',
    },

    placement: {
      title: 'Einstufungstest',
      question: 'Frage',
      of: 'von',
      level: 'Niveau',
      previous: 'Zurück',
      next: 'Weiter',
      finish: 'Prüfung beenden',
      submitting: 'Wird eingereicht...',
      submitError: 'Fehler beim Einreichen der Prüfung',
    },

    placementResult: {
      title: 'Ergebnis des Einstufungstests',
      correctAnswers: 'Richtige Antworten',
      of: 'von',
      yourLevel: 'Ihr Sprachniveau',
      score: 'Punktzahl',
      viewCourses: 'Geeignete Kurse anzeigen',
      goToDashboard: 'Zu meinem Dashboard',
      backToHome: 'Zurück zur Startseite',
    },

    level: {
      A1: {
        title: 'Anfänger (A1)',
        desc: 'Sie können einfache alltägliche Ausdrücke verstehen und verwenden. Auf diesem Niveau können Sie sich vorstellen und einfache Fragen stellen.',
      },
      A2: {
        title: 'Grundlegend (A2)',
        desc: 'Sie können in vertrauten Situationen kommunizieren. Sie verstehen einfache Sätze und können über alltägliche Bedürfnisse sprechen.',
      },
      B1: {
        title: 'Mittelstufe (B1)',
        desc: 'Sie können über vertraute Themen sprechen und einfache Texte schreiben. Sie verstehen alltägliche Gespräche.',
      },
      B2: {
        title: 'Obere Mittelstufe (B2)',
        desc: 'Sie können mit relativer Flüssigkeit sprechen. Sie verstehen komplexere Texte und können Ihre Meinung äußern.',
      },
      C1: {
        title: 'Fortgeschritten (C1)',
        desc: 'Sie können komplexe Texte verstehen und fließend sprechen. Geeignet für akademische und berufliche Zwecke.',
      },
      C2: {
        title: 'Experte (C2)',
        desc: 'Sie können wie ein Muttersprachler sprechen. Sie verstehen alle Texte und können leicht kommunizieren.',
      },
    },
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fa');
  const [dir, setDir] = useState<'rtl' | 'ltr'>('rtl');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && translations[savedLang]) {
      setLanguage(savedLang);
      setDir(savedLang === 'fa' ? 'rtl' : 'ltr');
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    setDir(lang === 'fa' ? 'rtl' : 'ltr');
    localStorage.setItem('language', lang);
    document.documentElement.dir = lang === 'fa' ? 'rtl' : 'ltr';
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    const keys = key.split('.');
    let value: any = translations[language];
    
    for (const k of keys) {
      if (value && typeof value === 'object' && k in value) {
        value = value[k];
      } else {
        return key;
      }
    }
    
    return typeof value === 'string' ? value : key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}